# Generated by Django 5.1.3 on 2024-12-01 18:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0006_alter_userprofile_invited_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcodes',
            name='created_at',
            field=models.DateTimeField(auto_created=datetime.datetime(2024, 12, 1, 21, 52, 29, 814982)),
        ),
    ]
