# Generated by Django 5.1.3 on 2024-12-01 19:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0007_alter_verificationcodes_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='inveted_by',
            new_name='invited_by',
        ),
        migrations.AlterField(
            model_name='verificationcodes',
            name='created_at',
            field=models.DateTimeField(auto_created=datetime.datetime(2024, 12, 1, 22, 28, 3, 298629)),
        ),
    ]
