# Generated by Django 5.1.3 on 2024-12-01 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0008_rename_inveted_by_userprofile_invited_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcodes',
            name='created_at',
            field=models.DateTimeField(auto_created=datetime.datetime(2024, 12, 1, 23, 54, 4, 149421)),
        ),
    ]
